vscode:
  extensions:
    - vsls-contrib.codetour
    - gabrielgrinberg.auto-run-command

tasks:
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
      { "auto-run-command.rules": [ { "command": "codetour.startTour" } ] }
      EOF
      exit
